language: android
dist: trusty
jdk: oraclejdk8

env:
  global:
    - ADB_INSTALL_TIMEOUT=8

android:
  components:
     - tools
     - platform-tools
     - build-tools-29.0.2
     - android-29
     - extra-android-support
     - extra-google-google_play_services
     - extra-google-m2repository
     - extra-android-m2repository

licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'android-sdk-preview-license-.+'

script:
  - ./gradlew assemble
